<a href="https://colab.research.google.com/github/andresvillamayor/BigData-Pro/blob/main/BigData_Pro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Proyecto de Big Data 
Andrés Villamayor 
Universidad Comunera

In [153]:
#importando librerias
import pandas as pd 
from  google.colab import drive 

In [154]:
drive.mount("/content/drive")
#montar mi drive para los archivos 


Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [155]:
data = pd.read_csv("/content/drive/My Drive/UCOM-BIGDATA/datatweet-07112020-v4.csv", sep="," , engine="python")

In [156]:
data.head()

id  ...       origen_usuario
0  1325088888629686274  ...             Asuncion
1  1325088260394192897  ...  paraguay - asuncion
2  1325087432262422528  ...   Asuncion, Paraguay
3  1325082531125977091  ...   Asuncion, PARAGUAY
4  1325082492513247233  ...            Paraguay 

[5 rows x 14 columns]

In [157]:
#usar el texto para (ver el corpus para el analisis de sentimiento)
#importamos la libreria NLTK ( Natural Lenguage Tool Kit)
import nltk
#nltk.download('stopwords') # ya se importo la libreria
#nltk.download('punkt') # ya se importo la libreria

In [158]:
#importa la libreria de soptwords de nltk 
from nltk.corpus import stopwords
# Initialize the stopwords
stoplist = stopwords.words('spanish')

In [159]:
# datos de parada - verificacion que este en español 
print(stoplist)

['de', 'la', 'que', 'el', 'en', 'y', 'a', 'los', 'del', 'se', 'las', 'por', 'un', 'para', 'con', 'no', 'una', 'su', 'al', 'lo', 'como', 'más', 'pero', 'sus', 'le', 'ya', 'o', 'este', 'sí', 'porque', 'esta', 'entre', 'cuando', 'muy', 'sin', 'sobre', 'también', 'me', 'hasta', 'hay', 'donde', 'quien', 'desde', 'todo', 'nos', 'durante', 'todos', 'uno', 'les', 'ni', 'contra', 'otros', 'ese', 'eso', 'ante', 'ellos', 'e', 'esto', 'mí', 'antes', 'algunos', 'qué', 'unos', 'yo', 'otro', 'otras', 'otra', 'él', 'tanto', 'esa', 'estos', 'mucho', 'quienes', 'nada', 'muchos', 'cual', 'poco', 'ella', 'estar', 'estas', 'algunas', 'algo', 'nosotros', 'mi', 'mis', 'tú', 'te', 'ti', 'tu', 'tus', 'ellas', 'nosotras', 'vosotros', 'vosotras', 'os', 'mío', 'mía', 'míos', 'mías', 'tuyo', 'tuya', 'tuyos', 'tuyas', 'suyo', 'suya', 'suyos', 'suyas', 'nuestro', 'nuestra', 'nuestros', 'nuestras', 'vuestro', 'vuestra', 'vuestros', 'vuestras', 'esos', 'esas', 'estoy', 'estás', 'está', 'estamos', 'estáis', 'están', 'e

In [160]:
# creamos un data frame solo con el texto 
datatexto =  data['texto']
datatexto.head()

0    RT @cinthia_mora: Pablo Herken venció al COVID...
1    RT @DeporteTotal780: Gerardo Ortiz, Futbolista...
2    Gerardo Ortiz, Futbolista de Once Caldas \n\n"...
3    HOY / Covid-19: Ciudad del Este registra una i...
4    🌎🌏 La pandemia de covid-19 acumuló hasta hoy 4...
Name: texto, dtype: object

In [161]:
#funcion de limpiar el texto 
#librerias
from string import punctuation
from nltk import word_tokenize

def limpiar_texto (text):
    non_words = list(punctuation)
    text = ''.join([c for c in text if c not in non_words])
    tokens =  word_tokenize(text)
    return tokens

In [162]:
#crear una funcion 
#tokenizar los datos 
spanish_stopwords = stopwords.words('spanish')
def valor_token(tokens):
  vector_texto = []
  #normalizacion del texto 
  tokens = [w.lower() for w in tokens]
  tokens =  [w for w in tokens if not w in spanish_stopwords]
  for item in tokens:
        vector_texto.append((item))  
  return vector_texto

In [163]:
# Analizar sentimiento del corpus 
#!pip install spanish-sentiment-analysis
#Libreria de Analisis de Sentimiento  https://pypi.org/project/spanish-sentiment-analysis   ( creado por Elliot Hofman 2018)
from classifier import SentimentClassifier
#crear una funcion 
def analizar(cadena_texto):
  clf = SentimentClassifier()
  valor = clf.predict(cadena_texto)
  #print (cadena_texto,valor) 
  return valor

In [164]:
resultado_valor=[]
for tweet in datatexto:
  datos_limpios = limpiar_texto(tweet)
  datos_tokenizados = valor_token (datos_limpios)
  #print(datos_tokenizados)
  cadena_valor = ' '.join([str(elem) for elem in datos_tokenizados])
  #print (cadena_valor)
  #analizar sentimiento del corpus 
  valor = analizar(cadena_valor)
  resultado_valor.append(valor)  
  #print (resultado_valor)

#agregar al data frame original el valor del Analisis del Corpus 
print ('======================== Fin del proceso de Analisis ==================')


======================== Fin del proceso de Analisis ==================


In [165]:
#Se agrega la columan Pre = Prediccion del Analisis de Sentimiento al Data Frame original "data"
data['Pre'] = resultado_valor
#impimir data frame 
data.head()

id  ...       Pre
0  1325088888629686274  ...  0.493964
1  1325088260394192897  ...  0.032832
2  1325087432262422528  ...  0.032832
3  1325082531125977091  ...  0.188819
4  1325082492513247233  ...  0.002751

[5 rows x 15 columns]

In [166]:
#verificar los tipos de datos
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   id                       50 non-null     int64  
 1   texto                    50 non-null     object 
 2   Fecha                    50 non-null     object 
 3   retweet                  50 non-null     int64  
 4   favorite                 50 non-null     int64  
 5   dispositivo              50 non-null     object 
 6   codigo_usuario           50 non-null     int64  
 7   alias_de_usuario         50 non-null     object 
 8   nombre_usuario           50 non-null     object 
 9   fecha_de_usuario         50 non-null     object 
 10  descripcion_del_usuario  41 non-null     object 
 11  seguidores_de_usuario    50 non-null     int64  
 12  amigos_de_usuario        50 non-null     int64  
 13  origen_usuario           42 non-null     object 
 14  Pre                      50 

Verificar los Datos para normalizacion 
Uso de Lablel Encoder 
Eliminacion de Columnas que no aportan 


In [167]:
# Revision de los datos 
# Borrar los campos de id 
# Borrar el codigo de usuario  se tiene su nombre y su alias 
data.drop(['id','codigo_usuario'],axis = 'columns',inplace = True)
data.head()

texto  ...       Pre
0  RT @cinthia_mora: Pablo Herken venció al COVID...  ...  0.493964
1  RT @DeporteTotal780: Gerardo Ortiz, Futbolista...  ...  0.032832
2  Gerardo Ortiz, Futbolista de Once Caldas \n\n"...  ...  0.032832
3  HOY / Covid-19: Ciudad del Este registra una i...  ...  0.188819
4  🌎🌏 La pandemia de covid-19 acumuló hasta hoy 4...  ...  0.002751

[5 rows x 13 columns]

In [168]:
#cacular hace cuanto tiempo usa twitter el usuario 
#libreria 
import numpy as np
#
data['Fecha'] = pd.to_datetime(data['Fecha'])
data['fecha_de_usuario'] = pd.to_datetime(data['fecha_de_usuario'])
data['Tiempo'] = ((data['Fecha']-data['fecha_de_usuario'])/np.timedelta64(1,'Y')).astype(int)

In [169]:
#verificar dataframe 
data.head()

texto  ... Tiempo
0  RT @cinthia_mora: Pablo Herken venció al COVID...  ...     10
1  RT @DeporteTotal780: Gerardo Ortiz, Futbolista...  ...     10
2  Gerardo Ortiz, Futbolista de Once Caldas \n\n"...  ...      7
3  HOY / Covid-19: Ciudad del Este registra una i...  ...     10
4  🌎🌏 La pandemia de covid-19 acumuló hasta hoy 4...  ...      9

[5 rows x 14 columns]

In [176]:
#Uso de Lablel Encoder 
#importamos libreria 
from sklearn import preprocessing

#codificacion
#dispositivo 
leDispositivo  = preprocessing.LabelEncoder()
data['dispositivo'] = leDispositivo.fit_transform(data['dispositivo'])
#origen usuario
leOrigen_usuario  = preprocessing.LabelEncoder()
data['origen_usuario'] = leOrigen_usuario.fit_transform(data['origen_usuario'].astype(str))

data.head()

texto  ... Tiempo
0  RT @cinthia_mora: Pablo Herken venció al COVID...  ...     10
1  RT @DeporteTotal780: Gerardo Ortiz, Futbolista...  ...     10
2  Gerardo Ortiz, Futbolista de Once Caldas \n\n"...  ...      7
3  HOY / Covid-19: Ciudad del Este registra una i...  ...     10
4  🌎🌏 La pandemia de covid-19 acumuló hasta hoy 4...  ...      9

[5 rows x 14 columns]

In [175]:
# verificar la inversa del Label Encoder
leDispositivo.inverse_transform(data['dispositivo'])  
# 2 Android 
# 1 Web App de Twitter
# 3 IPhone 
# 0 TeetDeck

array(['3', '3', '3', '4', '3', '3', '3', '3', '3', '3', '3', '4', '3',
       '3', '3', '2', '3', '2', '3', '3', '3', '4', '3', '3', '0', '3',
       '3', '2', '3', '4', '1', '1', '2', '3', '2', '3', '4', '4', '3',
       '3', '4', '3', '3', '4', '4', '3', '3', '3', '3', '2'],
      dtype=object)

In [177]:
# Colocar los valores Buenos y Malos dentro del Data Frame 
# Dependiendo del valor de Pre
final = []
#Valor 0 =  Sentimiento NEGATIVO
#Valor 1 =  Sentimiento POSITIVO
for resultado in  data['Pre']:
  if resultado <= 0.5:
    x = 0
    final.append(x)
  else:
    x = 1
    final.append(x)

In [178]:
data['Final'] = final
data

texto  ... Final
0   RT @cinthia_mora: Pablo Herken venció al COVID...  ...     0
1   RT @DeporteTotal780: Gerardo Ortiz, Futbolista...  ...     0
2   Gerardo Ortiz, Futbolista de Once Caldas \n\n"...  ...     0
3   HOY / Covid-19: Ciudad del Este registra una i...  ...     0
4   🌎🌏 La pandemia de covid-19 acumuló hasta hoy 4...  ...     0
5   RT @LaNacionPy: 🔴 Seis países, entre ellos Din...  ...     0
6   RT @ParaguayTVHD: Inmunidad pos COVID-19: La i...  ...     0
7   @ObamaParaguayo @JOSEESCAURIZA @_erikaIvonne N...  ...     1
8   RT @LaNacionPy: #CoronavirusPy. Desde la XI Re...  ...     0
9   RT @LaNacionPy: #CoronavirusPy. Desde la XI Re...  ...     0
10  RT @LaNacionPy: 🔴 Seis países, entre ellos Din...  ...     0
11  RT @ParaguayTVHD: Inmunidad pos COVID-19: La i...  ...     0
12  RT @ParaguayTVHD: Inmunidad pos COVID-19: La i...  ...     0
13  Los últimos en ser vacunados contra el covid_1...  ...     0
14  RT @nvoscar: Muere el político argentino Pino ...  ...     1
15  Inmunidad pos COVID-19: La inmunidad al COVID-...  ...     0
16  Muere el político argentino Pino Solanas.\nEda...  ...     1
17  #CoronavirusPy. Desde la XI Región Sanitaria c...  ...     0
18  Salud reporta fallecimiento de menor de un año...  ...     0
19  RT @UNO650AM: Reportan muerte de un bebé de me...  ...     0
20  RT @trecepy: ▪️ El ministerio de Salud reportó...  ...     1
21  RT @Unicanal: 😢Un bebé de menos de 1 año fue v...  ...     0
22  RT @Unicanal: 😢Un bebé de menos de 1 año fue v...  ...     0
23  RT @cinthia_mora: Pablo Herken venció al COVID...  ...     0
24  𝗛𝗜𝗦𝗧𝗢𝗥𝗜𝗔𝗦 📰👥\n\nSi bien la OMS informó de caso...  ...     0
25  Casemiro y Hazard dieron positivo al covid-19 ...  ...     0
26  RT @LaNacionPy: 🔴 Seis países, entre ellos Din...  ...     0
27  🔴 Seis países, entre ellos Dinamarca, España y...  ...     0
28  RT @npyoficial: #Destacado El reporte diario d...  ...     0
29  RT @npyoficial: #Destacado El reporte diario d...  ...     0
30  #Destacado El reporte diario del covid-19 anun...  ...     0
31  #Destacado El reporte diario del covid-19 anun...  ...     0
32  📍¿Existe la posibilidad de una reinfección por...  ...     0
33  RT @FabianCosta1: Entre los 10 fallecidos por ...  ...     0
34  COVID-19: 703 casos positivos y 10 decesos htt...  ...     0
35  RT @hoypy: #Nacionales | Pablo Herken venció a...  ...     1
36  Cuantas guerras terminó Trump? Y la guerra com...  ...     0
37                 RT @hoypy: https://t.co/S7JdHyHoLT  ...     1
38  RT @FabianCosta1: Entre los 10 fallecidos por ...  ...     0
39  RT @cinthia_mora: Pablo Herken venció al COVID...  ...     0
40  RT @FabianCosta1: Entre los 10 fallecidos por ...  ...     0
41  Entre los 10 fallecidos por covid-19 este vier...  ...     0
42  Entre los 10 fallecidos por covid-19 este vier...  ...     0
43  Mientras tanto 5 personas de la Casa Blanca in...  ...     0
44  RT @hoypy: #Nacionales | Pablo Herken venció a...  ...     1
45  Los verdaderos "Muertos por Covid-19" https://...  ...     0
46  RT @cinthia_mora: Pablo Herken venció al COVID...  ...     0
47  RT @MedicinaUNA: HOY / Cero contagios de COVID...  ...     0
48  RT @pavap_py: En el contexto de la pandemia po...  ...     0
49  RT @LaNacionPy: Los italianos tendrán que resp...  ...     1

[50 rows x 15 columns]

Utilizando SVM MODEL  

In [193]:
#libreria 
from sklearn import svm
from sklearn import preprocessing
from sklearn import metrics
from sklearn.model_selection import train_test_split

#seleccion de datos 
df1 = data.iloc[:,2:3] #retweet
df2 = data.iloc[:,3:4] #favorito
df3 = data.iloc[:,4:5] #dispositivo
df4 = data.iloc[:,9:10] #seguidores 
df5 = data.iloc[:,10:11] # amigos 
df6 = data.iloc[:,13:14] # Tiempo de que usa Twitter
df7 = data.iloc[:,14:15] # Target
df = pd.concat([df1,df2,df3,df4,df5,df6,df7], axis = 1)
#print (df)
# Resultado Final 
y = df['Final']   # 1 Positivo  2 Negativo 
#Se usan todas las variables 
X = df.iloc[:,0:6]

# Split en train y test  ( se toma los datos de la misma semilla - random_state = 1 , el 30 % de los datos son para entrenamiento test_size = 0.3)
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size= 0.3, random_state = 1)

# Normalizacion a [0-1]
min_max_scaler_train = preprocessing.MinMaxScaler()
xNormTrain = pd.DataFrame(min_max_scaler_train.fit_transform(X_train.values))
min_max_scaler_test = preprocessing.MinMaxScaler()
xNormTest = pd.DataFrame(min_max_scaler_test.fit_transform(X_test.values))


#Ceracion de Clasificacion SVM 
clf = svm.SVC(kernel='rbf', max_iter=2000, probability=1) # kernel={linear, rbf, poly, sigmoid}
#Train the model using the training sets
clf.fit(xNormTrain, y_train)

#Predict the response for test dataset
y_pred = clf.predict(xNormTest)

print("\nTrain Score:",clf.score(xNormTrain, y_train))
print("\nAccuracy:",metrics.accuracy_score(y_test, y_pred))
metrics.precision_recall_fscore_support(y_test, y_pred, average=None)


Train Score: 0.8

Accuracy: 0.9333333333333333


(array([0.93333333, 0.        ]),
 array([1., 0.]),
 array([0.96551724, 0.        ]),
 array([14,  1]))